language: go
sudo: false
go:
  - 1.13
before_script:
script:
  - go get ./...
  - cd pipeline && go test ./... && cd -
  - cd logdb && go test ./... && cd -
  - cd tsdb && go test ./... && cd -
  - cd base && go test ./... && cd -
